[package]
name = "reinforcement_learning"
version = "0.1.0"
authors = ["Matteo De Carlo <matteo.dek@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
ndarray = "0.12.1"
ordered-float = "0.2.3"
lp-modeler = "0.3.2"
csv = "1.0.7"